title: Duckling
owner: "Cees van de Griend"
email: cees.van.de.griend@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A demo site with Jekyll to practish with HTML5, CSS3 
  and JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: cvdg

# Build settings
theme: minima
# plugins:
  # - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
